name: Build EXE from Python

on:
  workflow_dispatch:
    inputs:
      create-release:
        description: 'Create Release'
        required: true
        default: 'false'
        type: boolean
      release-tag:
        description: 'Release tag for GitHub Release (e.g., v1.0.0)'
        required: false
        default: 'v1.0.0'
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # Hoặc phiên bản Python bạn cần

    # 3. Install dependencies (from requirements.txt)
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Build EXE using PyInstaller
    - name: Build EXE
      run: |
        pyinstaller --onefile --name hdz_yt_downloader yt.py

    # 5. Upload the artifact (EXE file)
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: built-exe
        path: dist/hdz_yt_downloader.exe  # Đường dẫn đến file .exe sau khi build

    # 6. Create GitHub Release (Chỉ tạo release nếu `create-release` là true)
    - name: Create GitHub Release
      if: ${{ github.event.inputs.create-release == 'true' && github.event.inputs.release-tag != '' }}
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.release-tag }}
        files: dist/hdz_yt_downloader.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
